Name: Elixir CI

on:
  push:
    branches-ignore:
      - main

      jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp: [22.x]
        elixir: [1.9.4]
