name: Elixir CI

on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres/postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: jc6
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: jc6
    name: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        otp: [27.x]
        elixir: [1.18.3]
    steps:
        - uses: actions/checkout@v1.0.0

        - uses: erlef/setup-beam@v1
          with:
            otp-version: ${{ matrix.otp }}
            elixir-version: ${{ matrix.elixir }}

        - name: Install dependencies
          run: |
            mix local.rebar --force
            mix local.hex --force
            mix deps.get

        - name: Run tests
          run: |
            mix compile --force --warnings-as-errors
            mix test --cover
            env:
            MIX_ENV: test

        - name: Static Code Analysis
          run: |
            mix sobelow -v
            mix sobelow --exit --threshold=medium
            env:
            MIX_ENV: test